#!/usr/bin/env python3
"""
Scrape OpenAI API docs as individual markdown files from developers.openai.com.

The site publishes two machine-readable manifests of the API reference:

  /api/reference/index.md   the full navigation tree (resources, subresources,
                            methods). Every entry is served at `<path>/index.md`.
  /api/reference/llms.txt   a flat manifest with titles and descriptions. Every
                            entry is served at `<path>.md`.

Neither is a superset. index.md carries the current resource tree but omits the
streaming/websocket event pages and the section overviews; llms.txt carries
those but still lists the pre-restructure `resources/organization/*` paths,
which now serve short "generated by Stainless" placeholder stubs. This script
takes the union of both and drops the stubs at fetch time.

Discovery is plain HTTP, so it runs anywhere -- no browser required.
"""

import argparse
import json
import os.path
import re
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.parse import urljoin

import requests

BASE_URL = "https://developers.openai.com"
REF_PREFIX = "/api/reference/"
INDEX_URL = f"{BASE_URL}{REF_PREFIX}index.md"
LLMS_URL = f"{BASE_URL}{REF_PREFIX}llms.txt"

DOCS_DIR = Path("docs")
CACHE_FILE = DOCS_DIR / ".url_cache.json"
CACHE_VERSION = 2

# Paths under docs/ that this script does not manage and must never prune.
PRESERVED = {"plans"}

REQUEST_TIMEOUT = 60
DELAY_BETWEEN_REQUESTS = 0.15
MAX_RETRIES = 3
RETRY_BACKOFF = 2
DEFAULT_JOBS = 4

# A retired page that now serves a placeholder instead of real content. These
# are short and always carry this trailer.
STUB_MARKER = "This API reference page is generated by Stainless."
STUB_MAX_BYTES = 2000

MD_LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)\s]+)\)")


# --------------------------------------------------------------------------
# Discovery
# --------------------------------------------------------------------------


def _get(url: str) -> str:
    resp = requests.get(url, timeout=REQUEST_TIMEOUT)
    resp.raise_for_status()
    return resp.text


def discover_pages() -> list[dict]:
    """Build the page list from index.md and llms.txt.

    Each page is {"text", "path", "scheme"} where `path` is the slug relative to
    /api/reference/ and `scheme` selects the URL form that serves it:
    "index" -> <path>/index.md, "flat" -> <path>.md
    """
    print("Discovering pages...")

    pages: dict[str, dict] = {}

    print(f"  GET {INDEX_URL}")
    index_md = _get(INDEX_URL)
    for text, href in MD_LINK_RE.findall(index_md):
        if not href.startswith(REF_PREFIX) or not href.endswith("/index.md"):
            continue
        path = href[len(REF_PREFIX) : -len("/index.md")]
        pages.setdefault(path, {"text": text.strip(), "path": path, "scheme": "index"})
    print(f"    {len(pages)} pages from the navigation tree")

    before = len(pages)
    print(f"  GET {LLMS_URL}")
    llms_txt = _get(LLMS_URL)
    for text, url in MD_LINK_RE.findall(llms_txt):
        if not url.startswith(f"{BASE_URL}{REF_PREFIX}") or not url.endswith(".md"):
            continue
        path = url[len(BASE_URL) + len(REF_PREFIX) : -len(".md")]
        if path.endswith("llms-full") or path == "llms":
            continue
        pages.setdefault(path, {"text": text.strip(), "path": path, "scheme": "flat"})
    print(f"    {len(pages) - before} additional pages from the manifest")

    ordered = sorted(pages.values(), key=lambda p: p["path"])
    print(f"  {len(ordered)} pages total")
    return ordered


def source_url(page: dict) -> str:
    if page["scheme"] == "index":
        return f"{BASE_URL}{REF_PREFIX}{page['path']}/index.md"
    return f"{BASE_URL}{REF_PREFIX}{page['path']}.md"


# --------------------------------------------------------------------------
# Path mapping
# --------------------------------------------------------------------------


def local_path(page: dict) -> Path:
    """Map a page slug to its file under docs/.

    resources/audio                                  -> docs/audio/index.md
    resources/audio/subresources/speech/methods/create
                                                     -> docs/audio/speech/create.md
    resources/responses/streaming-events             -> docs/responses/streaming-events.md
    resources/$shared                                -> docs/shared/index.md
    resources/fine_tuning/subresources/methods       -> docs/fine_tuning/methods/index.md
    overview                                         -> docs/overview.md
    workload-identity-federation                     -> docs/workload-identity-federation.md
    """
    raw = page["path"].split("/")
    if raw and raw[0] == "resources":
        raw = raw[1:]

    def clean(segments: list[str]) -> list[str]:
        return [s.lstrip("$") for s in segments if s != "subresources"]

    # "methods" is only a marker when it introduces the trailing method name.
    # fine_tuning has a *subresource* named "methods", so a bare `in` test on
    # the segments would misfile it as fine_tuning's index page.
    if len(raw) >= 2 and raw[-2] == "methods":
        return DOCS_DIR.joinpath(*clean(raw[:-2]), f"{raw[-1]}.md")

    parts = clean(raw)
    if page["scheme"] == "index":
        return DOCS_DIR.joinpath(*parts, "index.md")
    return DOCS_DIR.joinpath(*parts[:-1], f"{parts[-1]}.md")


# --------------------------------------------------------------------------
# Content cleanup
# --------------------------------------------------------------------------


def strip_internal_ast(content: str) -> tuple[str, int]:
    """Drop fenced json blocks holding the doc generator's internal AST.

    The streaming/websocket event pages inline the generator's declaration graph
    ("kind": "HttpDeclProperty", "oasRef", ...) once per event, which balloons a
    single page past 20 MB. The surrounding headings, descriptions, schema names
    and example payloads are kept; only the AST dumps go.
    """
    lines = content.split("\n")
    out: list[str] = []
    removed = 0
    i = 0
    while i < len(lines):
        if lines[i].startswith("```json"):
            end = i + 1
            while end < len(lines) and not lines[end].startswith("```"):
                end += 1
            block = lines[i : end + 1]
            body = "\n".join(block)
            if '"kind": "HttpDecl' in body or '"oasRef"' in body:
                removed += 1
                i = end + 1
                continue
            out.extend(block)
            i = end + 1
            continue
        out.append(lines[i])
        i += 1

    cleaned = re.sub(r"\n{3,}", "\n\n", "\n".join(out))
    return cleaned, removed


def build_link_map(pages: list[dict]) -> dict[str, Path]:
    """Map every known page slug to its local file."""
    return {page["path"]: local_path(page) for page in pages}


def _normalize_ref(url: str) -> str | None:
    """Reduce an in-content link to a page slug, or None if it isn't one."""
    if not url.startswith(REF_PREFIX):
        return None
    slug = url[len(REF_PREFIX) :].split("#", 1)[0].split("?", 1)[0]
    for suffix in ("/index.md", ".md", "/"):
        if slug.endswith(suffix):
            slug = slug[: -len(suffix)]
            break
    return slug


class LegacyRefResolver:
    """Resolve legacy /docs/api-reference/<slug> links to canonical page slugs.

    The docs cross-reference each other almost entirely through the old
    platform.openai.com-era paths (`/docs/api-reference/runs/submitToolOutputs`),
    which bear no mechanical relation to the current tree. Rather than guess at
    an alias table, ask the site: it still serves redirects for these, and that
    redirect map is authoritative. Results are memoised, and in practice a whole
    run needs only a few dozen lookups.

    Unrecognised slugs redirect to the reference overview; that is the site's
    catch-all, not a real answer, so it counts as unresolved and the link is
    left pointing at openai.com.
    """

    PREFIX = "/docs/api-reference/"

    def __init__(self) -> None:
        self._cache: dict[str, str | None] = {}
        self._lock = threading.Lock()

    def resolve(self, url: str) -> str | None:
        if not url.startswith(self.PREFIX):
            return None
        slug = url[len(self.PREFIX) :].split("#", 1)[0].split("?", 1)[0].rstrip("/")
        if not slug:
            return None

        with self._lock:
            if slug in self._cache:
                return self._cache[slug]

        target = self._lookup(slug)
        with self._lock:
            self._cache[slug] = target
        return target

    def _lookup(self, slug: str) -> str | None:
        try:
            resp = requests.head(
                f"{BASE_URL}{self.PREFIX}{slug}", allow_redirects=True, timeout=REQUEST_TIMEOUT
            )
        except requests.RequestException:
            return None

        final = resp.url
        if not final.startswith(f"{BASE_URL}{REF_PREFIX}"):
            return None

        canonical = final[len(BASE_URL) + len(REF_PREFIX) :].split("#", 1)[0].rstrip("/")
        if canonical == "overview" and slug != "overview":
            return None
        return canonical


def fix_links(
    content: str, link_map: dict[str, Path], page: dict, legacy: "LegacyRefResolver"
) -> str:
    """Point links at local files where we have them, absolutise the rest.

    Nothing relative is left behind: a link we cannot resolve to a local file
    becomes an absolute developers.openai.com URL, so the mirror never contains
    a dangling local path. A handful of links are broken upstream too (e.g. the
    fine-tuning permission pages link to `../admin-api-keys`, which 404s on the
    site); those stay broken, but visibly so, and point at OpenAI rather than at
    a missing file here.
    """
    here = local_path(page).parent
    page_url = f"{BASE_URL}{REF_PREFIX}{page['path']}/"

    def replace(match: re.Match) -> str:
        text, url = match.group(1), match.group(2)

        if url.startswith(("http://", "https://", "#", "mailto:")):
            return match.group(0)

        absolute = url if url.startswith("/") else urljoin(page_url, url)[len(BASE_URL) :]

        slug = _normalize_ref(absolute) or legacy.resolve(absolute)
        if slug is not None:
            target = link_map.get(slug)
            if target is not None:
                rel = os.path.relpath(target, here).replace("\\", "/")
                return f"[{text}]({rel})"

        return f"[{text}]({BASE_URL}{absolute})"

    return MD_LINK_RE.sub(replace, content)


# --------------------------------------------------------------------------
# Fetching
# --------------------------------------------------------------------------


def fetch_markdown(url: str) -> tuple[str | None, int]:
    for attempt in range(MAX_RETRIES):
        try:
            resp = requests.get(url, timeout=REQUEST_TIMEOUT)
            if resp.status_code == 200:
                return resp.text, 200
            if resp.status_code in (403, 429, 500, 502, 503, 504) and attempt < MAX_RETRIES - 1:
                time.sleep(RETRY_BACKOFF**attempt)
                continue
            return None, resp.status_code
        except requests.RequestException:
            if attempt < MAX_RETRIES - 1:
                time.sleep(RETRY_BACKOFF**attempt)
                continue
            return None, 0
    return None, 0


def is_stub(content: str) -> bool:
    return len(content) < STUB_MAX_BYTES and STUB_MARKER in content


# --------------------------------------------------------------------------
# Pruning
# --------------------------------------------------------------------------


def prune(expected: set[Path]) -> list[Path]:
    """Delete managed files under docs/ that are no longer part of the site."""
    removed = []
    for path in sorted(DOCS_DIR.rglob("*.md")):
        rel = path.relative_to(DOCS_DIR)
        if rel.parts and rel.parts[0] in PRESERVED:
            continue
        if path not in expected:
            path.unlink()
            removed.append(path)

    for directory in sorted(DOCS_DIR.rglob("*"), reverse=True):
        if not directory.is_dir():
            continue
        rel = directory.relative_to(DOCS_DIR)
        if rel.parts and rel.parts[0] in PRESERVED:
            continue
        if not any(directory.iterdir()):
            directory.rmdir()

    return removed


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-discover",
        action="store_true",
        help="reuse the cached page list instead of refetching the manifests",
    )
    parser.add_argument(
        "--skip-existing",
        action="store_true",
        help="leave files that are already on disk alone (development shortcut)",
    )
    parser.add_argument(
        "--no-prune",
        action="store_true",
        help="keep local files that are no longer published by the site",
    )
    parser.add_argument(
        "--keep-internal-ast",
        action="store_true",
        help="do not strip the generator's internal AST json blocks",
    )
    parser.add_argument(
        "--jobs", type=int, default=DEFAULT_JOBS, help=f"parallel fetches (default {DEFAULT_JOBS})"
    )
    parser.add_argument(
        "--max-failures",
        type=int,
        default=10,
        help="exit non-zero if more than this many pages fail (default 10)",
    )
    return parser.parse_args(argv)


def load_cache() -> list[dict]:
    if not CACHE_FILE.exists():
        print("ERROR: no page cache found; run without --no-discover first.")
        sys.exit(1)
    data = json.loads(CACHE_FILE.read_text())
    if not isinstance(data, dict) or data.get("version") != CACHE_VERSION:
        print(f"ERROR: page cache is not version {CACHE_VERSION}; rerun discovery.")
        sys.exit(1)
    pages = data["pages"]
    print(f"Loaded {len(pages)} pages from cache")
    return pages


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    DOCS_DIR.mkdir(parents=True, exist_ok=True)

    print("=" * 64)
    print("OpenAI API docs scraper (developers.openai.com)")
    print(f"Output: {DOCS_DIR}/")
    print("=" * 64)

    pages = load_cache() if args.no_discover else discover_pages()
    if not args.no_discover:
        CACHE_FILE.write_text(
            json.dumps({"version": CACHE_VERSION, "pages": pages}, indent=2) + "\n"
        )
        print(f"  cache written to {CACHE_FILE}")

    # A collision means two slugs claim one file and one would clobber the other.
    seen: dict[Path, str] = {}
    for page in pages:
        target = local_path(page)
        if target in seen:
            print(f"ERROR: {seen[target]} and {page['path']} both map to {target}")
            return 2
        seen[target] = page["path"]

    link_map = build_link_map(pages)
    legacy = LegacyRefResolver()

    results = {"written": [], "skipped": [], "stub": [], "failed": []}
    ast_blocks = 0
    lock = threading.Lock()
    counter = {"n": 0}

    def handle(page: dict) -> None:
        nonlocal ast_blocks
        url = source_url(page)
        target = local_path(page)

        with lock:
            counter["n"] += 1
            i = counter["n"]

        if args.skip_existing and target.exists():
            with lock:
                results["skipped"].append(page["path"])
                print(f"[{i}/{len(pages)}] SKIP  {target}")
            return

        content, status = fetch_markdown(url)
        if content is None:
            with lock:
                results["failed"].append((page["path"], status))
                print(f"[{i}/{len(pages)}] FAIL  HTTP {status}  {url}")
            return

        if is_stub(content):
            with lock:
                results["stub"].append(page["path"])
                print(f"[{i}/{len(pages)}] STUB  {page['path']} (retired, not written)")
            return

        raw_len = len(content)
        removed = 0
        if not args.keep_internal_ast:
            content, removed = strip_internal_ast(content)
        content = fix_links(content, link_map, page, legacy)

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

        with lock:
            ast_blocks += removed
            results["written"].append(page["path"])
            note = ""
            if removed:
                note = f"  (stripped {removed} AST blocks, {raw_len:,} -> {len(content):,})"
            print(f"[{i}/{len(pages)}] OK    {target} {len(content):,} chars{note}")

        time.sleep(DELAY_BETWEEN_REQUESTS)

    with ThreadPoolExecutor(max_workers=max(1, args.jobs)) as pool:
        list(pool.map(handle, pages))

    pruned = []
    if not args.no_prune:
        by_path = {p["path"]: p for p in pages}
        # Failed fetches keep their existing file: a transient error is not
        # evidence the page was retired. Genuinely removed pages fall out of
        # the manifests and so are absent from `pages` entirely.
        kept_slugs = (
            results["written"] + results["skipped"] + [slug for slug, _ in results["failed"]]
        )
        pruned = prune({local_path(by_path[slug]) for slug in kept_slugs})

    print("\n" + "=" * 64)
    print("SUMMARY")
    print("=" * 64)
    print(f"  written:      {len(results['written'])}")
    print(f"  skipped:      {len(results['skipped'])}")
    print(f"  retired stub: {len(results['stub'])}")
    print(f"  pruned:       {len(pruned)}")
    print(f"  failed:       {len(results['failed'])}")
    if ast_blocks:
        print(f"  internal AST json blocks stripped: {ast_blocks:,}")

    if results["failed"]:
        print("\n  failures:")
        for path, status in results["failed"]:
            print(f"    HTTP {status}  {path}")

    if len(results["failed"]) > args.max_failures:
        print(f"\nFAILED: {len(results['failed'])} pages failed (limit {args.max_failures}).")
        return 1

    print(f"\nDone. {len(results['written'])} files written to {DOCS_DIR}/")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
